
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtFname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtSname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtavg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtRank = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtMath = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtEng = new javax.swing.JTextField();
        jtxtBus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtBio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtPhy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtAm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcmbCourseCode = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jtxtcom = new javax.swing.JTextField();
        jtxtChem = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnReset = new javax.swing.JButton();
        jbtnRanking = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnRanking1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Result System");
        setPreferredSize(new java.awt.Dimension(1380, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student ID:");

        jtxtId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        jtxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIdKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Firstname:");

        jtxtFname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Surname:");

        jtxtSname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Total Score:");

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Average:");

        jtxtavg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Ranking:");

        jtxtRank.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Math:");

        jtxtMath.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtMath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMathActionPerformed(evt);
            }
        });
        jtxtMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMathKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("English:");

        jtxtEng.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtEng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEngKeyTyped(evt);
            }
        });

        jtxtBus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtBus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBusKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Biology:");

        jtxtBio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtBio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBioKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Physics:");

        jtxtPhy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPhy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPhyKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Add Math:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Business:");

        jtxtAm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtAm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtAmKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Course Code:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Chemistry:");

        jcmbCourseCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbCourseCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C98123", "C98234", "C98345", "C98567" }));
        jcmbCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCourseCodeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Computing:");

        jtxtcom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtcom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtcomKeyTyped(evt);
            }
        });

        jtxtChem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChemKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtRank, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtavg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtFname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcmbCourseCode, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtId, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtcom, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jtxtBio)
                            .addComponent(jtxtEng)
                            .addComponent(jtxtMath)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPhy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtAm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtBus)
                            .addComponent(jtxtChem))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtMath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jtxtEng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtxtBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jtxtcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmbCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jtxtChem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jtxtPhy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jtxtAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jtxtBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtavg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 450));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4), "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36))); // NOI18N

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 540, 450));

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 4))));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Course Code", "Math", "English", "Biology", "Computing", "Chemistry", "Physics", "Add Math", "Business", "Total Score ", "Average", "Ranking"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1290, 180));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 680, -1, -1));

        jbtnRanking.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnRanking.setText("Ranking");
        jbtnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 680, -1, -1));

        jbtnTranscript.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnTranscript.setText("Transcript");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, -1, -1));

        jbtnRanking1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnRanking1.setText("Delete");
        jbtnRanking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRanking1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRanking1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 130, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbCourseCodeActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField temp=null;
        for(Component c:jPanel1.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                temp=(JTextField)c;
                temp.setText(null);
            }
        }
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        jtxtTranscript.append("Student Result\n"+"======================\n"+
                "Math= "+jtxtMath.getText()+
                "\nEnglish= "+jtxtEng.getText()+
                "\nBiology= "+jtxtBio.getText()+
                "\nComputing= "+jtxtcom.getText()+
                "\nChemistry= "+jtxtChem.getText()+
                "\nPhysics= "+jtxtPhy.getText()+
                "\nAdditional Math= "+jtxtAm.getText()+
                "\nBusiness= "+jtxtBus.getText()+
                "\nTotal Score= "+jtxtTotal.getText()+
                "\nAverage= "+jtxtavg.getText()+
                "\nRank= "+jtxtRank.getText());
    }//GEN-LAST:event_jbtnTranscriptActionPerformed
private JFrame Frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        Frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(Frame,"Confirm if you want to exit","Exit System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSnameActionPerformed

    private void jbtnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRankingActionPerformed
       double [] R=new double[14];
       R [0]=Double.parseDouble(jtxtMath.getText());
       R [1]=Double.parseDouble(jtxtEng.getText());
       R [2]=Double.parseDouble(jtxtBio.getText());
       R [3]=Double.parseDouble(jtxtcom.getText());
       R [4]=Double.parseDouble(jtxtChem.getText());
       R [5]=Double.parseDouble(jtxtPhy.getText());
       R [6]=Double.parseDouble(jtxtAm.getText());
       R [7]=Double.parseDouble(jtxtBus.getText());

       R[8]=(R[0]+R[1]+R[2]+R[3]+R[4]+R[5]+R[6]+R[7])/8;
       R[9]=R[0]+R[1]+R[2]+R[3]+R[4]+R[5]+R[6]+R[7];
       
       String Avg=String.format("%.0f", R[8]);
       jtxtavg.setText(Avg);
       
       String Total=String.format("%.0f", R[9]);
       jtxtTotal.setText(Total);
       
       if(R[9]>=700){
           jtxtRank.setText("1st");
       }
       else if(R[9]>=600){
           jtxtRank.setText("2nd");
       }
       else if(R[9]>=500){
           jtxtRank.setText("3rd");
       }
       else if(R[9]>=200){
           jtxtRank.setText("Passed");
       }
       else {
           jtxtRank.setText("Failed");
       }
       
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       model.addRow(new Object[]{
           jtxtId.getText(),
           jcmbCourseCode.getSelectedItem(),
           jtxtMath.getText(),
           jtxtEng.getText(),
           jtxtBio.getText(),
           jtxtcom.getText(),
           jtxtChem.getText(),
           jtxtPhy.getText(),
           jtxtAm.getText(),
           jtxtBus.getText(),
           jtxtTotal.getText(),
           jtxtavg.getText(),
           jtxtRank.getText(),
       });
    }//GEN-LAST:event_jbtnRankingActionPerformed

    private void jtxtMathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMathActionPerformed
       
    }//GEN-LAST:event_jtxtMathActionPerformed

    private void jtxtMathKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMathKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtMathKeyTyped

    private void jtxtEngKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEngKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtEngKeyTyped

    private void jtxtBioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBioKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtBioKeyTyped

    private void jtxtcomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcomKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtcomKeyTyped

    private void jtxtChemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChemKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtChemKeyTyped

    private void jtxtPhyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhyKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtPhyKeyTyped

    private void jtxtAmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtAmKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtAmKeyTyped

    private void jtxtBusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtBusKeyTyped

    private void jtxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIdKeyTyped
        char inum=evt.getKeyChar();
        if(!(Character.isDigit(inum))||(inum==KeyEvent.VK_BACK_SPACE)||(inum==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_jtxtIdKeyTyped

    private void jbtnRanking1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRanking1ActionPerformed
       DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
       if(jTable1.getSelectedRow()==-1){
           if(jTable1.getSelectedRow()==0){
               JOptionPane.showMessageDialog(null,"No data to delete","Student result",JOptionPane.OK_OPTION);
           }else{
               JOptionPane.showMessageDialog(null,"Select a Row to delete","Student result",JOptionPane.OK_OPTION);
           }
       }
       else{
           model.removeRow(jTable1.getSelectedRow());
       }
    }//GEN-LAST:event_jbtnRanking1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnRanking;
    private javax.swing.JButton jbtnRanking1;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JComboBox jcmbCourseCode;
    private javax.swing.JTextField jtxtAm;
    private javax.swing.JTextField jtxtBio;
    private javax.swing.JTextField jtxtBus;
    private javax.swing.JTextField jtxtChem;
    private javax.swing.JTextField jtxtEng;
    private javax.swing.JTextField jtxtFname;
    private javax.swing.JTextField jtxtId;
    private javax.swing.JTextField jtxtMath;
    private javax.swing.JTextField jtxtPhy;
    private javax.swing.JTextField jtxtRank;
    private javax.swing.JTextField jtxtSname;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextArea jtxtTranscript;
    private javax.swing.JTextField jtxtavg;
    private javax.swing.JTextField jtxtcom;
    // End of variables declaration//GEN-END:variables
}
